language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"

env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1

install:
  - pip install pipenv
  - pipenv install --dev

script:
  - pipenv run -- pytest ecobici/test.py -s -v